{
	"data": "ENC[AES256_GCM,data:/dXXrknwNI7qqmCso8jwvGwX1ewSl2X0u9Zu0nYepCeCWPAeFnJ5UDJA+bQpPIaRvq1AS7cj4rUN6xe6k7q3lYWU,iv:nQowbbiK5oI9zS/qbVhRkf8xoLQ+yCm1zqZM56nWiKc=,tag:CbSiDOTO2cCQSFxO9d+/FQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1tnwk468t43gcu6e6j2fmrr0dj075cjhm0939v9lnh4nqqsnc74jqma892g",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSXNTQVVYZDdLN0R4SXVG\nZ2tQUTRwdUJ3alJjU3ZJejF2ZUxSeG4vSlVBCmFDOGE5cnJDZER3RExmNldDQThI\nT2dwRVhJVU0vSVlFZGdrOEN2YzlXeWMKLS0tIGp3TngzWjdZS21XYmI3V3JiZUNO\nM0daRWNRWXMraDlYYUpnY3lvWURUdWcKxWxSz5VWakY+yCll9BoWUrhQ3Ewp9kx/\nh46IFwOGl+YBS70/y9lOrBZPJHfLlA9K/2ARni2ryIEa4gZKHyJMGQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-10-19T17:10:46Z",
		"mac": "ENC[AES256_GCM,data:mGUrHxzQV8bO+ogV8/BOAhqUd5TRj7eyNN2wSVyXdJozPeD7Ypj65AUi6OmKpr1YZT5O2Tjmmqj3NXJfAff7z1lQxPi+NQdglc9oAOYVvWTouy3NE3kEVN2np5FU/c/HIqshbaJnGsRCBfgQpNguwLYrPw1+a/pKqhN7K/1LSs4=,iv:fEyUUFJyMrZQLsbfktnSpzE/EarI99IkU4hySoa7DSc=,tag:5j4zZ6xqpljFgTuVjTDhcw==,type:str]",
		"version": "3.11.0"
	}
}
